name: Security Scan

on:
  pull_request:
    branches:
      - main

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - run: flutter pub get

      - name: Create local.properties
        run: echo "sdk.dir=$ANDROID_HOME" > android/local.properties

      - name: Build project
        run: flutter build apk --debug

      - name: Perform Analysis
        uses: github/codeql-action/analyze@v3