name: Flutter Tests

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Flutter Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache Flutter
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-flutter-${{ hashFiles('**/pubspec.lock') }}

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.41.4'

      - run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-fatal-warnings --no-fatal-infos

      - name: Run Tests
        run: flutter test